### ISSUE TITLE
CSD02 Ballot Issue - JADN as Normative

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#10]
Although I like JADN, I am not yet prepared for Annex 1 (the JADN schema) to be the overriding normative definition of a slpf. I would need more time and experimenting to fully understand annex 1. I understand the main text of the document. I'm not conversant enough yet to know Annex 1 says the same thing. So I would prefer text to be normative for now. Ie change first conformance clause in 3.1 to refer to main text instead of annex.

**Comment by jmbrule** [comment]
Per the discussions at the F2F, the document was modified IAW your comment.  I.e, the tables are authoritative

**Comment by jmbrule** [comment]
Suggest close

**Comment by jmbrule** [comment]
Per the face to face discussions that occurred on Jan 11, 2019, the language spec will remove the JADN aspects and the property tables are normative.  Suggest close
