### ISSUE TITLE
CSD02 Ballot Comment - Update

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#11]
Where is the use case for the update action in an slpf? I don't see it on GitHub. Apologies if I just can't find it and I'll remove objection. But if no use case exists, I object to update-file being included. I am concerned on feature creep in profiles and I think we need different profiles for different security functions. But if there is a use case for a core slpf function which uses update, then I'll retract this.

**Comment by jmbrule** [comment]
Cisco provided a use case for update via email and jmbrule created the usecase on the googledrive (located at https://docs.google.com/document/d/17Ros6hE_xlofHq2McZUZCaZiDJd676JyQqLZYyjyWfA/edit )  A subsequent email from Cisco (dated August1) stated that the use case as presented on the googledrive captures the gist of the use case.

**Comment by jmbrule** [comment]
The use case has been uploaded to the ~incoming directory on the drive.  Suggest close
