### ISSUE TITLE
CSD02 Ballot Comment - response_type default

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#12]
I think the default response_type should be ‘complete’ instead of 'none'

**Comment by jmbrule** [comment]
AGREED! but need ot bounce it off the SC first

**Comment by jmbrule** [comment]
Should not close this one yet.  At the F2F the issue of the 'default' response type was discussed at great length in the context of the language subcommittee.  The gist of the discussion was:  IN the event that the response_type argument is not specified, then the default should be defined at the language level.  The two 'favorites' were 'none' and 'complete'.  Comments for 'complete' were along the lines that the vast majority of the commands will require complete responses, therefore should be default.  Comments for 'none' were along the lines that some very simple actuators (such as IoT) may not be capable of supporting 'complete' therefore need to accommodate the least common denominator.

**Comment by jmbrule** [comment]
Based on further discussions (at both the lang and AP SC) was decided that 'complete' as default response_type.  Suggest close
