### ISSUE TITLE
SLPF Response

### ISSUE THREAD

**Issue by alevere** [oasis-tcs/openc2-apsc-stateless-packet-filter#122]
An issue for some environment is determining which actuator responded if an orchestrator receives three responses that appear similar (200 ok). 
I propose we require an SLPF to return asset_id or asset_tuple in order to determine what device sent a response. Helpful when true source is hidden (NAT, LB) or when using a broadcast/message bus.

**Comment by Vasileios-Mavroeidis** [comment]
agree.

Just to add some context. This is an issue when we send ONE command to multiple actuators. The UUID of the command is the same,  so in the case of 3 responses, no matter if they are successful or not we don't know which response applies to a particular actuator since all of them use the same identifier.

**Comment by jmbrule** [comment]
This is an issue that will be common to a lot of profiles in systems that have a pub/sub or multicast.  Having an 'actuator' field in the response makes sense to me.  Question, should we close the issue here and reopen it on the language channel?

**Comment by Vasileios-Mavroeidis** [comment]
Yep, this is a general issue.  It should be handled at the language-spec level

**Comment by jmbrule** [comment]
Alex, I do not feel good about closing this issue and reopen on the LSC because you brought it up and I think it would be disrespectful of me to close your issue.    Do you agree with me and Vasileios, and if so will you close this one and move to LSC?

**Comment by jmbrule** [comment]
@alevere , will you read over this thread and let me close it here and reintroduce it at the Lang level?

**Comment by alevere** [comment]
That makes sense to me, sorry for missing this.
