### ISSUE TITLE
CSD02 Ballot Comment - Error responses

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#13]
The responses to error conditions do not just apply to the query slpf In 2.3.7, but apply to many commands - Ie Put this error handling in it's own section (or repeat a bunch of times). 

I disagree to overspecifiying response (eg 501 if does not support access rules). I’d prefer ‘SHOULD’ for 501 but allow 400 and 500 as well. My concern is for actuator complexity and also for backwards compatibility as new things are added. I wouldn’t want an slpf to fail conformance because it didn’t implement an error code for something it doesn’t do (ie don’t distinguish between an illegal target and an optional target that wasn’t implemented.
Similar comment in 2.3.1 - "MUST NOT do OK” is correct but “MUST respond 501” replace with “SHOULD respite 501” etc.

I played around with some prototype code to better explain my point. I made minimalistic actuator called haha (see https://github.com/oasis-open/openc2-lycan-beam/tree/master/haha/erlang/haha) and I took a middle road wrt error responses. The 3 choices I see for error responses are:

1. give different error responses  for different error conditions including all the command combo's that the actuator does not support. Ie distinguish between action=deny (which is allowed optionally in openc2 but not supported by haha) and action=block (which is not allowed by openc2) with different error messages.
2. give different error responses for different error conditions except don't distinguish between optional terms not supported and terms that are not allowed - eg action=deny ad action=block would return the same 'bad action' message.
3. do not distinguish types of errors and just give same error (500 internal server error) no matter what caused. This is very easy to do with Erlang 'let it crash' approach.

Haha implements choice 2. I also implemented hahax1 (x1 for first experiment - see https://github.com/oasis-open/openc2-lycan-beam/tree/master/haha/erlang/hahax1) for choice 3. 
I didn't implement choice 1 since it would be a lot of work and I think 2,3 is enough to make my point.

Haha takes 168 lines of Erlang if you strip out comments and debug logging. Hahax1 takes only 58 lines. In other words, the code for informing the producer about it's errored command takes 2.9 times as much code as a simple one-size-fits-all error. Given choice 1 involves writing error conditions for hundred-plus unused openc2 terms (haha uses only 1 action , 1 target, and no args), it is safe to assume it would increase the bloat even more.

I think the issue comes down to introducing complexity on the OpenC2-producer  or on the OpenC2-consumer. I vote OpenC2-producer. The OpenC2-producer complexity would come during development and debugging. It would have to handle both the verbose/precise error messages and the one-size-fits-all error messages, as well as debugging is harder. Debugging only occurs once whereas production messages occur forever and at much more scale. And the producer can 'afford' more complexity than simpler actuators as in IoT.

Also note once in production, the main beneficiary to detailed error responses (and complex code to generate the details) are hackers.

Note I'm not arguing you can't have detailed error messages - I'm just arguing for 'should' instead of 'shall'.

**Comment by jmbrule** [comment]
Agreed, will systematically change the SHALLS to MAYS in the actuator profile.  Will go with the approach of repeating a bunch of times vice a 'generic error handling' section.  Dont close this one yet, need time to cross check all those

**Comment by jmbrule** [comment]
OK, I THINK I got all these covered,  Going to close it, but subject to reviewers identifying any that were missed

**Comment by jmbrule** [comment]
OBE, your suggestion was taken exactly as proposed
