### ISSUE TITLE
CSD02 Ballot Comment - Requiring Optional for Producers

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#14]
The specification in many places requires OpenC2 Producers to implement options that are optional for OpenC2 Consumers to implement. For example 2.3.3 requires Producers to implement ip_addr but it is (correctly IMHO) optional for Consumers. This will result in a Producer that makes a perfectly good product for it’s usecasss (eg working with clouds such as AWS, Azure, Openstack) to be out of conformance because it won’t support an optional feature of some actuator it will never talk to (and still could talk to the actuator without that feature). I believe a better way to handle this would be with ‘conformance profiles’ per OASIS conformance guidelines so you could have a basic conforming and a ‘ip_addr’ a conforming (or whatever).

**Comment by jmbrule** [comment]
I disagree with this approach because (my opinion) it defeats the purpose of a standard.  If optional for both the commander and the actuator, then you have a situation where the commander implements ip_addr and the actuator implements ip_connection.  Both are 'compliant' but NOT inter-operable.

**Comment by jmbrule** [comment]
At the Face to Face that occurred on July 26, the general consensus was:  
The OpenC2 Command Consumer will be required to implement ip_connection OR ip_addr
The OpenC2 Command Producers will be required to implement ip_connection AND ip_addr.
The advantages and disadvantages associated with creating two profiles vs making ip_connection required and ip_addr optional in all cases vs creation of conformance profiles within the actuator profile were discussed. 
Suggest closing this issue as of the August 8 Actuator Profile SC meeting

**Comment by jmbrule** [comment]
Would like to close this issue based on the discussion at the July 26 F2F.  Will close this on September 10 unless notified otherwise

**Comment by jmbrule** [comment]
This issue is repeated in ballot comment 3.

**Comment by jmbrule** [comment]
This issue was addressed via creation of more conformance clauses
