### ISSUE TITLE
Ballot Comment WD03 - Conformance To LS 1.0

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#19]
I propose Section 3.2 item 1 sub-bullet 1.1 be changed from
`MUST be conformant with Version 1.0 of the Language Specification`
to  
`
MUST be conformant with Version 1.0 (or higher) of the Language Specification`.
This would obviate the need to update this specification every time the language spec is updated

**Comment by jmbrule** [comment]
Good idea, will change the text exactly as proposed.  I will leave this topic open for a couple more days to see if anyone else weighs in.  If not, will close it

**Comment by jmbrule** [comment]
Am closing this one, the modification was accepted exactly as proposed

**Comment by jmbrule** [comment]
Am closing this one, the modification was accepted exactly as proposed

**Comment by jmbrule** [comment]
Reopened due to TAB comment (look at https://github.com/oasis-tcs/openc2-apsc-stateless-packet-filter/issues/34 )  Conflicting comments, need to work out

**Comment by sparrell** [comment]
There are two cases we need to cover:
- so that we don't need to update each AP spec every minor version change to Language Spec
- so that an AP profile V1 conformant device at time X doesn't become non-conformant at time Y due to a new version of the Language Spec

Given this does not need to be decided now (since neither case applies until future versions of either Language Spec or SPLF) so the F2F in Phoenix agreed to defer (ie to not add the 'or higher').
