### ISSUE TITLE
Conformance language should map to schema rather than property tables

### ISSUE THREAD

**Issue by jmbrule** [oasis-tcs/openc2-apsc-stateless-packet-filter#22]

**Comment by jmbrule** [comment]
The current text in section 3.1 states that the serialization must be syntactically correct in accordance with the property tables.  Should be in accordance with the schema to be consistent with OASIS rules.  
In particular: "All normative computer language definitions must also be provided in separate plain text files;
Each text file must be referenced from the Work Product; and
Where any definition in these separate files disagrees with the definition found in the specification documentation, the definition in the separate file prevails.
TC Process section 2.2.5"

**Comment by jmbrule** [comment]
Here is a direct paste from a related github issue identified by Duncan Sparrell:  (#10 )
Although I like JADN, I am not yet prepared for Annex 1 (the JADN schema) to be the overriding normative definition of a slpf. I would need more time and experimenting to fully understand annex 1. I understand the main text of the document. I'm not conversant enough yet to know Annex 1 says the same thing. So I would prefer text to be normative for now. Ie change first conformance clause in 3.1 to refer to main text instead of annex.

**Comment by sparrell** [comment]
Would it be possible to show somewhere an electronic "proof" that the property tables and JADN are the same. My understanding is this is possible. If it was "public", I'll withdraw my objection because although I haven't read and understood everything in JADN, I have read and understood the property tables. I suspect I'm not the only one who understands the property tables better than the JADN.

**Comment by jmbrule** [comment]
Pull request https://github.com/oasis-tcs/openc2-apsc-stateless-packet-filter/pull/43 , understand this issue is dependent on lang speck deliberations and deliberations within the context of this spec

**Comment by jmbrule** [comment]
Reject this change and close issue.  OBE due to the separation of JADN into its own spec
