### ISSUE TITLE
Support IP Address and CIDR/Subnets

### ISSUE THREAD

**Issue by jmbrule** [oasis-tcs/openc2-apsc-stateless-packet-filter#26]

**Comment by jmbrule** [comment]
This is related to PR comment submitted via email (https://lists.oasis-open.org/archives/openc2-comment/201811/msg00009.html )

A change in the language spec was not accommodated by the SLPF.  In order to be consistent with the Language spec and to support use cases identified for Packet filtering the following modifications are needed in the SLPF:  

Add a new target to the language specification to accommodate CIDR notation for IPv4 and IPv6 addresses  
Modify table 2.1.2-1 in the SLPF to include the new targets.
Update table 2.3-1 to in the SLPF to include the new targets in the command matrix 
Add new subsection to section 2.3.1 to indicate that the new target is appropriate for the 'allow' and deny action
Update table 3-1 in the SLPF to include the commands affected by the new target
Update the conformance targets in section 3 of the SLPF to reflect the new target

**Comment by davaya** [comment]
This is related to PR comment on the language spec https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00008.html

**Comment by sparrell** [comment]
I believe @jmbrule created https://github.com/oasis-tcs/openc2-apsc-stateless-packet-filter/pull/54 to attempt to address this issue

**Comment by jmbrule** [comment]
@sparrell  Well sort of;  I generated the pull request to attempt to address the issue, but acknowledge the fact that the language subcommittee needs to reach a consensus first, and did some 'guesswork' wrt what the new target will actually be.  Was my intent to have it hashed out at the F2F in the lang spec then will modify the SLPF accordinly

**Comment by jmbrule** [comment]
Suggest close, resolved via #67.  Will reopen if the LSC does not reach consensus.  Please advise if it needs to remain open, otherwise will close on Feb 19 at 15:00 eastern
