### ISSUE TITLE
Table of contents missing in the MD version of the SLPF specification 

### ISSUE THREAD

**Issue by jmbrule** [oasis-tcs/openc2-apsc-stateless-packet-filter#27]
This comment applies to the transfer and language specifications as well.  The HTML and PDF versions have a table of contents, but was not generated for the MD version.  Suggest incorporating a TOC

**Comment by dlemire60** [comment]
Working with OASIS TCADMIN to address this in the publishing process.

Related to Language Spec [issue 172](https://github.com/oasis-tcs/openc2-oc2ls/issues/172). No corresponding issue submitted for the HTTPS Spec, but we should be consistent across three documents.

**Comment by davaya** [comment]
Closed by Pull Request #73.
Duncan, Joe or Jason need to actually close the issue.
https://github.com/orgs/oasis-tcs/teams?utf8=%E2%9C%93&query=openc2
