### ISSUE TITLE
CSD01 Ballot Comment - Relation to other docs

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#5]
Comment by Duncan Sparrell on CSD01 ballot:
`Either in the introduction directly, or by referencing some other document, the document needs to explain what an actuator profile is, and how it relates to language specification and transport and especially to other actuator profiles (ie one device can have more than one profile, including custom profiles).`

**Comment by jmbrule** [comment]
OK, I will try to add it in but would appreciate some suggested text

**Comment by jmbrule** [comment]
I attempted to address this comment with some boilerplate stuff in the intro section then I moved some of hte current intro section to the purpose scope section.  Can you look at it and tell me if it is on track?

**Comment by jmbrule** [comment]
When you get an opportunity to do so, will you look at the new introduction?

**Comment by jmbrule** [comment]
Will leave open for now, but would like to get the subcommittee to state support (or disagreement) with the proposed boilerplate on hte Aug 8 AP SC meeting

**Comment by jmbrule** [comment]
Based on discussions at the Jan 11, 2019 F2F, this issue will be addressed with common material in section 1 of all the specifications.  Dave Lemire will act as the focal point to ensure consistency.  Suggest closing this issue

**Comment by jmbrule** [comment]
Front matter in all three specs address this issue.  Please advise if it needs to remain open, otherwise will close at 08:00 eastern on Feb 26
