### ISSUE TITLE
Should use the word 'consumer' or 'producer' instead of product where appropriate

### ISSUE THREAD

**Issue by jmbrule** [oasis-tcs/openc2-apsc-stateless-packet-filter#55]
This comment was provided by Duncan Sparrell (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00044.html )
In the context of OASIS specifications, product as a specific meaning and there are multiple instances where the SLPF used 'product' when the word 'device', 'producer' or 'consumer' should have been used

**Comment by jmbrule** [comment]
Agreed, look at pull request 62

**Comment by dlemire60** [comment]
I haven't searched the document for instances of "product", but all of the changes in PR #62 look correct and appropriate to me.
