### ISSUE TITLE
Use an example other than 'toaster' for IoT

### ISSUE THREAD

**Issue by jmbrule** [oasis-tcs/openc2-apsc-stateless-packet-filter#56]
This comment was provided by Duncan Sparrel (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00043.html)  

Toaster is not an good example for an IoT.  Suggest one of the following: 
pacemaker, 
drone, 
CPAP, 
motion-detector, 
insulin pump, 
front-door-lock, 
car-brakes, 
commuter-train-speed-control
--

**Comment by jmbrule** [comment]
I agree with the reviewer, Unless someone objects, may I use 'front-door-lock'?  A lock is a reasonable example of something that does a  'defense' action.

**Comment by alevere** [comment]
agree

**Comment by jmbrule** [comment]
Pull request number #61

**Comment by dlemire60** [comment]
I like the smart door lock as a better example.  It would be helpful if the pull requests were

1. more meaningfully named and
2. linked with the issues they address
