### ISSUE TITLE
JADN Notation is atypical

### ISSUE THREAD

**Issue by jmbrule** [oasis-tcs/openc2-apsc-stateless-packet-filter#58]
Comment provided by Duncan Sparrell (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00041.html )

Dislike the JADN notation ( [1, "drop_process", "Drop-Process", ["[0"], ""] )

**Comment by davaya** [comment]
JADN is currently defined in the Language Spec.   This issue is the same as https://github.com/oasis-tcs/openc2-oc2ls/issues/165.

**Comment by jmbrule** [comment]
This issue is post 1.0 (pending the creation of the JADN spec).  Closed per Jan 30, 2019 AP-SC
