### ISSUE TITLE
CSD01 Ballot Comment - Transport Section

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#6]
Comment by Duncan Sparrell on CSD01 ballot:
`I believe there should be a transport section to the document (unless the previous issue is resolved by some other document that pulls language/actuator/trans­port together). Ie I think the actuator profiles are the document that ties it all together. if not, then say what is.`

**Comment by jmbrule** [comment]
OpenC2 is intended to be agnostic of the underlying message fabric, that is to say that OpenC2 could work on http/ tls, could work on an OpenDXL message fabric, MQTT pub sub environment etc.  The lang spec and actuator profiles are focusing on the 'payload' part of the protocol data unit.   Agree that we should add prose that refers to the transfer specs.

**Comment by sparrell** [comment]
@jmbrule - I agree the openc2 language is "agnostic of the underlying message fabric". However I thought an Actuator Profile (of which slpf is one) defined what a slpf device did. I agree the slpf should not 'require' a particular transport. But I do think the slpf profile should include a section on transport that just contains optional choice (including custom) for transport so that a real device can pick which subset it used. The value add of this section is not in the generic "could be anything" text in the slpf spedification but the value is in the subtending document that shows which options were chosen (eg the x_bawnl custom profile,https://github.com/oasis-tcs/openc2-cap/blob/master/bawnl.cap.md, meets the slpf profile but defines https transport (non standard in this case since no https openc2 spec exists yet).

**Comment by jmbrule** [comment]
OK, I had a phrase in my mind but not on paper in the conformance section and it is not exactly fair to expect everyone to be mind readers....  My 'plan' was to put something in the conformance section along the lines of 
"MUST support the use of one or more transfer specifications (such as https) that identify underlying transport protocols such that an authenticated, ordered, lossless, delivery of OpenC2 messages that are uniquely identified is provided."
This is one of these chicken and egg problems.  We dont have any transfer specs to reference so is kind of a 'black hole routing'. 
I am wondering if all the specs (lang, act profiles, transfer specs) need some boilerplate up front that states the scope of a particular spec and points the reader.

**Comment by jmbrule** [comment]
Leave open for now, need time for the subcommittee to review the boilerplate material up front and the modified conformance bullet in section 3

**Comment by jmbrule** [comment]
Front matter has been created for all three specifications.  The conformance section of this specification has a clause regarding transport.  Suggest closing

**Comment by jmbrule** [comment]
This issue is identical to issue #9 , which is currently open. Will close this one because it is a repeat
