### ISSUE TITLE
ICMP target needed

### ISSUE THREAD

**Issue by jmbrule** [oasis-tcs/openc2-apsc-stateless-packet-filter#69]

**Comment by jmbrule** [comment]
The current spec does not cover the ICMP use cases adequately.  The IP connection target has the next protocol field (ICMP is 1) but does not cover the different ICMP types that we need to distinguish (such as redirect, ping, source quench etc) 
Suggest adding an ICMPv4 and ICMPv6 target types for the deny and allow commands

**Comment by alevere** [comment]
See https://www.iana.org/assignments/icmp-parameters/icmp-parameters.xhtml and https://www.iana.org/assignments/icmpv6-parameters/icmpv6-parameters.xhtml

**Comment by jmbrule** [comment]
Here are three proposals:  

ONE:  Overload the ipv*_connection target.  
Add text in section 2.1.2.2 
"Semantics / requirements as they pertain to ipv*_connection
•	Proto= TCP - 5 tuple is proto=TCP, src-ip, dst-ip, src-port, dest-port
•	Proto= UDP - 5 tuple is proto=UDP, src-ip, dst-ip, src-port, dest-port
•	Proto= ICMP - 5 tuple is proto=ICMP, src-ip, dst-ip, icmp-type, icmp-code
•	Proto= any other - 5 tuple is proto, src-ip, dst-ip, unused, unused

TWO:  Create a new target type(s) for ICMP with properties of src address, dest address and ICMP type

THREE:  Expand the ip_connection to a 'six-tuple' vice five tuple to accommodate the ICMP type

Please provide your insights/ feedback in this matter.  

Also, it would be most helpful if you indicated your preferred approach or indicate that oyu have no preference

**Comment by jmbrule** [comment]
BTW, I have a *slight* preference for option ONE (overload the ip_connection).  
I do think we need to modernize it.  There are multiple protocols other than TCP and UDP that utilize ports.  Do not see the advantage of artificially constraining src and dst port to those two transport protocols only

**Comment by jmbrule** [comment]
I received two out of band communications: 
Dave Kemp prefers option TWO
Vasileios prefers ONE
Sparrel prefers ONE (implied because he proposed it) 
Vishi prefers ONE

**Comment by dlemire60** [comment]
Based on Dave K's observations that target space isn't a limited resource and there are likely <10 protocols that would actually need to be added as targets, I'm joining him in supporting option TWO. It really does seem cleaner to me to define each target individually and unambiguously.

That said, I'd also agree that explicitly defining scope of the existing connection target to include any protocol that fits its pattern of source & dest IPs and ports makes sense. The endpoint then would appear to be two more inclusive ip?_connection targets and a handful of other targets that don't fit that construct.

**Comment by sparrell** [comment]
Can we agree that best practice is to block by default? If yes, would you show the set of commands with option 2 that would accomplish this? I am assuming that we will allow some sort of "*" or "all" parameter with option 1 but that is not practical with option 2. I guess we could add yet another target that is protocol (without the additional fields) to handle the 'rest' that we don't specify exclusively. I still think option 1 is better. A related question, if we go with option 2, would we change to a 4-tuple and have TCP and UDP each their own target since we are giving the other 'major' protocols each their own target, it makes more sense to me for TCP and UDP to be treated like the others under option 2. I still vote option 1, but if we do go with option 2 then it should be consistent.

**Comment by jmbrule** [comment]
According to my 'strawpoll' (ack that it is a small cross section) I see four people in favor of option 1, two in favor of option 2.  
IN the context of 'target space isn't a limited resource ', I will grant you that we are not receiving a monthly bill for each target we define, but I would like to avoid the situation where we create a very large number of targets.  I do not pretend to know where that point is.   I will ack that industry appears to be overloading the five-tuple, so it would appear that we can at least try it.  If we are in error, then I do not see anything stopping us from adding the ICMP target in version 1.1.  It is a heck of a lot easier to add a target later than it is to try to remove one after the fact.  
Given that I prefer 'option two', I will cook up a pull request for option two and defer the creation of a pull request for 'option one' to a person who is a champion for the approach. 
At the end of the day, we can make either work so not going to dig my heels.

**Comment by jmbrule** [comment]
When you get a chance, look at PR #71 .   Give me a thumbs up or tell me I am a moron.   Would like to resolve this ICMP type and code issue as soon as practical

**Comment by dlemire60** [comment]
The PR seems straightforward and to-the-point. I'll defer to those with stronger networking expertise than I on whether the various 5-tuple descriptions need any tuning.

One question:  for the ipv6_connection should the IPv6 versions of protocols like ICMP should the v6 versions be explicitly named? Or is it sufficient / implicit that it's in an IPv6_connection type?

**Comment by jmbrule** [comment]
Don't know for sure, but assume it is implicit and given that I explicitly stated the appropriate RFC, we should be OK

**Comment by Vasileios-Mavroeidis** [comment]
I think its fine. No big difference and simplicity is aided that way.

**Comment by davaya** [comment]
Closed by Pull Request #71.
Duncan, Joe or Jason need to close this issue.
