### ISSUE TITLE
CSD01 Ballot Comment - AWS Custom Actuator Profile

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#7]
Comment by Duncan Sparrell on CSD01 ballot:
`I particularly care about the AWS and Azure NACL use cases (yes I need to write up Azurew NACL) and I believe this profile meets those cases. But I think we need to document the custom extensions for both AWS and Azure to validate both the concept of extensions and the the specifics of those two implementations.`

**Comment by jmbrule** [comment]
It was my understanding that there was going to be some experimentation with the concept of 'device profiles'.   It would seem that the notion of the Azure profile or AWS profile is beyond the scope of the SLPF profile.  
Please provide suggested text or a suggested means to resolve this comment

**Comment by sparrell** [comment]
Yes experimentation is going on with bawnl (https://github.com/oasis-tcs/openc2-cap/blob/master/bawnl.cap.md) a custom slpf extension for aws. I would prefer this comment stay open for now. I'm still not convinced the best way to define relationships between custom ap's and specification ap's; nor on best way to deal with one device with multiple specification ap's.

**Comment by jmbrule** [comment]
good idea (to leave the comment open).  I was thinking (but never wrote down) that a particular box, instance, vm or whatever would have one, two or more profiles.  When the producer sends the command it will have ACTION TARGET ACTUATOR.  The ACTUATOR will imply the profile we are talking about.  SO if I had a shinybox that can do SLPF and it can do (notional) MALWARESCAN then my command would be something like DENY IP_ADDR SLPF (specifier that uniquely identifies the actuator such as a hostname or whatever).  
Later I could send a command like SCAN FILE MALWARESCAN (specifier that uniquely identifies the actuator such as a hostname or whatever).  The specifier could be the same, but when it gets it, it knows which profile to use. 
This might have been easier to do during one of the profile meetings.

**Comment by jmbrule** [comment]
The language spec has a section regarding the importation of data models (to include profiles other than OASIS specifications) and all three specs have front matter that indicates that does not preclude a particular implementation having more than one profile.  We do need to do some more work on the profile writing guide, but that is beyond the scope of hte SLPF.  Suggest closing this issue

**Comment by alevere** [comment]
Duncan,

Does the extension work need to hold up the WD to CSD this week?
I believe the current slpf accommodates AWS NACLs, but I won't say I have tested it.
My thought is that extension work can come later. 
E.g.
aws ec2 create-network-acl-entry --network-acl-id acl-5fb85d36 --ingress --rule-number 100 --protocol udp --port-range From=53,To=53 --cidr-block 0.0.0.0/0 --rule-action allow

**Comment by jmbrule** [comment]
I do not understand why this issue is still open.  We have the SLPF that has multiple conformance targets.  We have the ability to create a custom actuator profile which seems to address the initial concern that Duncan identified in June 2018.  (in fact the Symantec product version 1.2 does exactly that).  We can import a namespace.  
Suggest close

**Comment by sparrell** [comment]
I would not have felt comfortable closing until someone actually did what comment requested ie made a CAP for AWS and Azure based on SLPF. Although that has not actually been done (if it has please give me the 2 URLs), the plugfest New Context open source shows it would be possible to do.

So I am OK with closing now.

iPhone, iTypo, iApologize
________________________________
