### ISSUE TITLE
Component Names in All Caps

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-apsc-stateless-packet-filter#76]
The Language Spec is no longer refers to "component names" and formats the defined terms from Section 1.2 with initial caps, not all caps.

ACTION -> Action
TARGET -> Target
etc.

We found that it was more confusing having 3 ways to spell a single word: ACTION, Action, or action, or even `action`. It didn't seem to aid in understanding to make the distinction of a component name, so eliminated it and removed those all-caps terms.

I recommend you do the same, but I didn't want to overhaul your Sections 1.8 and 2.0.

**Comment by alevere** [comment]
Could you go ahead and make a pull request for this?

**Comment by romanojd** [comment]
I created pull request #79 to address this issue.
