### ISSUE TITLE
CSD02 Ballot Comment - Transport Section

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-apsc-stateless-packet-filter#9]
Reiterating my comment on Ballot CSD01 (#6) I feel there should be a transport section to the profile. Note the conformance section states:
`"MUST support the use of one or more published OpenC2 transfer specifications which identify underlying transport protocols such that an authenticated, ordered, lossless, delivery of uniquely identified OpenC2 messages is provided."`
which is good but violates OASIS Conformance Guidelines (http://docs.oasis-open.org/templates/TCHandbook/ConformanceGuidelines.html) Rule 6 states
`"Rule 6: A Conformance Clause must NOT introduce new normative statements that could instead have been part of the specification main body"`
so we need something in the main body (ie a section on transport).

**Comment by jmbrule** [comment]
The boilerplate material in section 1 of the SLPF discusses how the language spec, actuator profiles and transfer specs related to each other, then the conformance section points back to section 1.

**Comment by jmbrule** [comment]
Would like to close this one upon your review of the boiler plate material for all three specs (language, SLPF and HTTP/TLS)
Suggest close

**Comment by jmbrule** [comment]
Would like to close this issue based on the boilerplate material created for all three specs.  Please advise if it needs to stay open, otherwise will close at 08:00 Eastern on Feb 26
